branch-defaults:
  development:
    environment: shop-api-dev
  master:
    environment: shop-api
  staging:
    environment: shop-api-staging
global:
  application_name: r2-d2-shop-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ebadminfitco
  repository: null
  sc: git
  workspace_type: Application
